name: PHPUnit

on:
  push:
    branches: [ "main-test", "dev-test" ]
  pull_request:
    branches: [ "main-test", "dev-test" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run test suite
      run: composer run-script test